import type { ImageSourcePropType } from 'react-native';

/**
 * Dados simulados (mock) para a aplicação Spotiflow
 * Baseado fielmente nos elementos de tela do Spotify
 */

export interface Track {
  id: string;
  title: string;
  artist: string;
  album: string;
  duration: string;
  durationSeconds: number;
  coverUrl: string;
  liked: boolean;
}

export interface Playlist {
  id: string;
  title: string;
  subtitle: string;
  author: string;
  coverUrl: string;
  coverSource?: ImageSourcePropType;
  isMixed?: boolean;
  isPinned?: boolean;
  isDownloaded?: boolean;
  tracksCount: number;
  tracks: Track[];
}

export interface Category {
  id: string;
  title: string;
  color: string;
  imageUrl: string;
}

export interface FriendActivity {
  id: string;
  name: string;
  avatarUrl: string;
  avatarSource?: ImageSourcePropType;
  currentTrack?: string;
  currentArtist?: string;
  lastActive: string;
  playlists: Playlist[];
}

export interface ChatMessage {
  id: string;
  sender: 'me' | 'them';
  text: string;
  time: string;
  sharedTrack?: Track;
}

export interface DirectMessage {
  id: string;
  senderName: string;
  avatarUrl: string;
  avatarSource?: ImageSourcePropType;
  previewText: string;
  date: string;
  messages: ChatMessage[];
}

// Faixa atual em reprodução (conforme o mini player)
export const CURRENT_TRACK: Track = {
  id: 'cazuza-exagerado',
  title: 'Exagerado',
  artist: 'Cazuza',
  album: 'Exagerado',
  duration: '3:34',
  durationSeconds: 214,
  coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&q=80',
  liked: true,
};

// Playlists da Home e Biblioteca do usuário principal (Jão)
export const MOCK_PLAYLISTS: Playlist[] = [
  {
    id: 'echos-of-us',
    title: 'Echos of us',
    subtitle: 'Playlist mixada • Jão',
    author: 'Jão',
    coverUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&q=80',
    coverSource: require('../../assets/images/echos-of-us.png'),
    isMixed: true,
    isDownloaded: true,
    tracksCount: 15,
    tracks: [
      {
        id: 'track-ff7-1',
        title: 'One-Winged Angel',
        artist: 'Nobuo Uematsu',
        album: 'Final Fantasy VII Original Soundtrack',
        duration: '4:26',
        durationSeconds: 266,
        coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-ff7-2',
        title: 'Hollow',
        artist: 'Yosh, Nobuo Uematsu',
        album: 'Final Fantasy VII Remake OST',
        duration: '6:12',
        durationSeconds: 372,
        coverUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-witcher-1',
        title: 'Silver for Monsters...',
        artist: 'Marcin Przybyłowicz, Percival',
        album: 'The Witcher 3: Wild Hunt OST',
        duration: '2:19',
        durationSeconds: 139,
        coverUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-witcher-2',
        title: 'The Fields of Ard Skellig',
        artist: 'Marcin Przybyłowicz',
        album: 'The Witcher 3: Wild Hunt OST',
        duration: '3:09',
        durationSeconds: 189,
        coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-ff7-3',
        title: 'Main Theme of Final Fantasy VII',
        artist: 'Nobuo Uematsu',
        album: 'Final Fantasy VII OST',
        duration: '6:28',
        durationSeconds: 388,
        coverUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80',
        liked: false,
      },
      {
        id: 'track-witcher-3',
        title: 'Geralt of Rivia',
        artist: 'Marcin Przybyłowicz',
        album: 'The Witcher 3: Wild Hunt OST',
        duration: '2:22',
        durationSeconds: 142,
        coverUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-ff7-4',
        title: "Aerith's Theme",
        artist: 'Nobuo Uematsu',
        album: 'Final Fantasy VII OST',
        duration: '4:18',
        durationSeconds: 258,
        coverUrl: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-witcher-4',
        title: 'Steel for Humans',
        artist: 'Marcin Przybyłowicz, Percival',
        album: 'The Witcher 3: Wild Hunt OST',
        duration: '1:27',
        durationSeconds: 87,
        coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80',
        liked: false,
      },
      {
        id: 'track-witcher-5',
        title: 'Kaer Morhen',
        artist: 'Marcin Przybyłowicz',
        album: 'The Witcher 3: Wild Hunt OST',
        duration: '2:34',
        durationSeconds: 154,
        coverUrl: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=600&q=80',
        liked: true,
      },
      CURRENT_TRACK,
      {
        id: 'track-2',
        title: 'Codinome Beija-Flor',
        artist: 'Cazuza',
        album: 'Cazuza',
        duration: '2:32',
        durationSeconds: 152,
        coverUrl: 'https://images.unsplash.com/photo-1445985543470-41f30c08f107?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-3',
        title: 'O Tempo Não Para',
        artist: 'Cazuza',
        album: 'O Tempo Não Para',
        duration: '4:38',
        durationSeconds: 278,
        coverUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80',
        liked: false,
      },
      {
        id: 'track-4',
        title: 'Ideologia',
        artist: 'Cazuza',
        album: 'Ideologia',
        duration: '4:06',
        durationSeconds: 246,
        coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-5',
        title: 'Pro Dia Nascer Feliz',
        artist: 'Barão Vermelho',
        album: 'Barão Vermelho 2',
        duration: '4:28',
        durationSeconds: 268,
        coverUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-6',
        title: 'Segredos',
        artist: 'Frejat',
        album: 'Amor Pra Recomeçar',
        duration: '3:52',
        durationSeconds: 232,
        coverUrl: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=600&q=80',
        liked: false,
      },
    ],
  },
  {
    id: 'my-peace',
    title: 'My peace',
    subtitle: 'Playlist • Jão',
    author: 'Jão',
    coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
    isPinned: true,
    isDownloaded: true,
    tracksCount: 10,
    tracks: [
      {
        id: 'track-peace-1',
        title: 'Vento no Litoral',
        artist: 'Legião Urbana',
        album: 'V',
        duration: '6:06',
        durationSeconds: 366,
        coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-peace-2',
        title: 'Como Nossos Pais',
        artist: 'Elis Regina',
        album: 'Falso Brilhante',
        duration: '4:40',
        durationSeconds: 280,
        coverUrl: 'https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-peace-3',
        title: 'Coração Vagabundo',
        artist: 'Caetano Veloso, Gal Costa',
        album: 'Domingo',
        duration: '2:25',
        durationSeconds: 145,
        coverUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-peace-4',
        title: 'Travessia',
        artist: 'Milton Nascimento',
        album: 'Travessia',
        duration: '4:15',
        durationSeconds: 255,
        coverUrl: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=600&q=80',
        liked: false,
      },
      {
        id: 'track-peace-5',
        title: 'Drão',
        artist: 'Gilberto Gil',
        album: 'Um Banda Um',
        duration: '3:13',
        durationSeconds: 193,
        coverUrl: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-peace-6',
        title: 'Clube da Esquina Nº 2',
        artist: 'Milton Nascimento, Lô Borges',
        album: 'Clube da Esquina',
        duration: '3:38',
        durationSeconds: 218,
        coverUrl: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-peace-7',
        title: 'O Leãozinho',
        artist: 'Caetano Veloso',
        album: 'Bicho',
        duration: '3:03',
        durationSeconds: 183,
        coverUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-peace-8',
        title: 'Anunciação',
        artist: 'Alceu Valença',
        album: 'Anjo Avesso',
        duration: '3:24',
        durationSeconds: 204,
        coverUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-peace-9',
        title: 'Pais e Filhos',
        artist: 'Legião Urbana',
        album: 'As Quatro Estações',
        duration: '5:08',
        durationSeconds: 308,
        coverUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=600&q=80',
        liked: true,
      },
      {
        id: 'track-peace-10',
        title: 'Águas de Março',
        artist: 'Elis Regina, Antônio Carlos Jobim',
        album: 'Elis & Tom',
        duration: '3:32',
        durationSeconds: 212,
        coverUrl: 'https://images.unsplash.com/photo-1525994886773-080587e161c2?w=600&q=80',
        liked: false,
      },
    ],
  },
  {
    id: 'on-my-mind',
    title: 'on my mind',
    subtitle: 'Playlist mixada • Jão',
    author: 'Jão',
    coverUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&q=80',
    isMixed: true,
    isDownloaded: true,
    tracksCount: 10,
    tracks: [
      {
        id: 'mind-1',
        title: 'Starboy',
        artist: 'The Weeknd, Daft Punk',
        album: 'Starboy',
        duration: '3:50',
        durationSeconds: 230,
        coverUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&q=80',
        liked: true,
      },
      {
        id: 'mind-2',
        title: 'Blinding Lights',
        artist: 'The Weeknd',
        album: 'After Hours',
        duration: '3:20',
        durationSeconds: 200,
        coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80',
        liked: true,
      },
      {
        id: 'mind-3',
        title: 'Passionfruit',
        artist: 'Drake',
        album: 'More Life',
        duration: '4:58',
        durationSeconds: 298,
        coverUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&q=80',
        liked: false,
      },
      {
        id: 'mind-4',
        title: 'Nights',
        artist: 'Frank Ocean',
        album: 'Blonde',
        duration: '5:07',
        durationSeconds: 307,
        coverUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80',
        liked: true,
      },
      {
        id: 'mind-5',
        title: 'Snooze',
        artist: 'SZA',
        album: 'SOS',
        duration: '3:21',
        durationSeconds: 201,
        coverUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
        liked: true,
      },
      {
        id: 'mind-6',
        title: 'goosebumps',
        artist: 'Travis Scott, Kendrick Lamar',
        album: 'Birds in the Trap Sing McKnight',
        duration: '4:03',
        durationSeconds: 243,
        coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80',
        liked: true,
      },
      {
        id: 'mind-7',
        title: 'Die For You',
        artist: 'The Weeknd',
        album: 'Starboy',
        duration: '4:20',
        durationSeconds: 260,
        coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&q=80',
        liked: true,
      },
      {
        id: 'mind-8',
        title: "God's Plan",
        artist: 'Drake',
        album: 'Scorpion',
        duration: '3:18',
        durationSeconds: 198,
        coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80',
        liked: false,
      },
      {
        id: 'mind-9',
        title: 'Pink + White',
        artist: 'Frank Ocean',
        album: 'Blonde',
        duration: '3:04',
        durationSeconds: 184,
        coverUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&q=80',
        liked: true,
      },
      {
        id: 'mind-10',
        title: 'Kill Bill',
        artist: 'SZA',
        album: 'SOS',
        duration: '2:33',
        durationSeconds: 153,
        coverUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&q=80',
        liked: true,
      },
    ],
  },
  {
    id: 'dyanassics-jao',
    title: 'Dyanassics + Jão',
    subtitle: 'Playlist • Spotify Match',
    author: 'Spotify',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80',
    isDownloaded: false,
    tracksCount: 10,
    tracks: [
      {
        id: 'match-1',
        title: 'Idiota',
        artist: 'Jão',
        album: 'Pirata',
        duration: '3:15',
        durationSeconds: 195,
        coverUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&q=80',
        liked: true,
      },
      {
        id: 'match-2',
        title: 'Me Lambe',
        artist: 'Jão',
        album: 'SUPER',
        duration: '2:55',
        durationSeconds: 175,
        coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&q=80',
        liked: true,
      },
      {
        id: 'match-3',
        title: 'Bixinho',
        artist: 'Duda Beat',
        album: 'Sinto Muito',
        duration: '3:17',
        durationSeconds: 197,
        coverUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&q=80',
        liked: true,
      },
      {
        id: 'match-4',
        title: 'Por Supuesto',
        artist: 'Marina Sena',
        album: 'De Primeira',
        duration: '3:06',
        durationSeconds: 186,
        coverUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&q=80',
        liked: true,
      },
      {
        id: 'match-5',
        title: 'A Cor É Rosa',
        artist: 'Silva',
        album: 'Brasileiro',
        duration: '3:45',
        durationSeconds: 225,
        coverUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&q=80',
        liked: false,
      },
      {
        id: 'match-6',
        title: 'Vermelho',
        artist: 'Gloria Groove',
        album: 'Lady Leste',
        duration: '2:33',
        durationSeconds: 153,
        coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&q=80',
        liked: true,
      },
      {
        id: 'match-7',
        title: 'Alinhamento Milenar',
        artist: 'Jão',
        album: 'SUPER',
        duration: '3:23',
        durationSeconds: 203,
        coverUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&q=80',
        liked: true,
      },
      {
        id: 'match-8',
        title: 'Essa Eu Fiz Pro Nosso Amor',
        artist: 'Jão',
        album: 'Anti-Herói',
        duration: '3:07',
        durationSeconds: 187,
        coverUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&q=80',
        liked: true,
      },
      {
        id: 'match-9',
        title: 'Dando Mais um Tempo',
        artist: 'Duda Beat',
        album: 'Te Amo Lá Fora',
        duration: '3:34',
        durationSeconds: 214,
        coverUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
        liked: false,
      },
      {
        id: 'match-10',
        title: 'Amarelo, Azul e Branco',
        artist: 'ANAVITÓRIA, Rita Lee',
        album: 'COR',
        duration: '3:21',
        durationSeconds: 201,
        coverUrl: 'https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=600&q=80',
        liked: true,
      },
    ],
  },
  {
    id: 'liked-songs',
    title: 'musicas curtidas do ian',
    subtitle: 'Playlist • Jão',
    author: 'Jão',
    coverUrl: 'https://images.unsplash.com/photo-1499415479124-43c32433a620?w=600&q=80',
    isDownloaded: true,
    tracksCount: 12,
    tracks: [
      {
        id: 'liked-suv-prata',
        title: 'SUV PRATA',
        artist: 'LEALL, Rock Danger, Babidi',
        album: 'SUV PRATA',
        duration: '3:01',
        durationSeconds: 181,
        coverUrl: 'https://images.unsplash.com/photo-1499415479124-43c32433a620?w=600&q=80',
        liked: true,
      },
      {
        id: 'liked-quer-voar',
        title: 'Quer Voar',
        artist: 'Matuê',
        album: 'Quer Voar',
        duration: '2:55',
        durationSeconds: 175,
        coverUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&q=80',
        liked: true,
      },
      {
        id: 'liked-talvez-voce-precise',
        title: 'Talvez você precise de mim',
        artist: 'Veigh, Supernova Ent',
        album: 'Talvez você precise de mim',
        duration: '3:28',
        durationSeconds: 208,
        coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80',
        liked: true,
      },
      {
        id: 'liked-gorilla-roxo',
        title: 'Gorilla Roxo',
        artist: 'Matuê',
        album: 'Gorilla Roxo',
        duration: '2:47',
        durationSeconds: 167,
        coverUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
        liked: true,
      },
      {
        id: 'liked-clareou',
        title: 'Clareou (Trilha Sonora Original)',
        artist: 'Thiaguinho, Negra Li',
        album: 'Clareou',
        duration: '3:40',
        durationSeconds: 220,
        coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80',
        liked: true,
      },
      {
        id: 'liked-anos-luz',
        title: 'Anos Luz',
        artist: 'Matuê',
        album: 'Anos Luz',
        duration: '3:13',
        durationSeconds: 193,
        coverUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&q=80',
        liked: true,
      },
      {
        id: 'liked-kenny-g',
        title: 'Kenny G',
        artist: 'Matuê',
        album: 'Kenny G',
        duration: '2:48',
        durationSeconds: 168,
        coverUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=600&q=80',
        liked: true,
      },
      {
        id: 'liked-maquina-tempo',
        title: 'Máquina do Tempo',
        artist: 'Matuê',
        album: 'Máquina do Tempo',
        duration: '3:42',
        durationSeconds: 222,
        coverUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=600&q=80',
        liked: true,
      },
      {
        id: 'liked-conexoes',
        title: 'Conexões de Máfia',
        artist: 'Matuê, Rich The Kid',
        album: 'Conexões de Máfia',
        duration: '3:10',
        durationSeconds: 190,
        coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80',
        liked: true,
      },
      {
        id: 'liked-vampiro',
        title: 'Vampiro',
        artist: 'Matuê, WIU, Teto',
        album: 'Vampiro',
        duration: '3:43',
        durationSeconds: 223,
        coverUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&q=80',
        liked: true,
      },
      {
        id: 'liked-flow-espacial',
        title: 'Flow Espacial',
        artist: 'Teto, WIU, Matuê',
        album: 'Flow Espacial',
        duration: '2:59',
        durationSeconds: 179,
        coverUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80',
        liked: true,
      },
      {
        id: 'liked-novo-balanco',
        title: 'Novo Balanço',
        artist: 'Veigh',
        album: 'Dos Prédios Deluxe',
        duration: '2:52',
        durationSeconds: 172,
        coverUrl: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=600&q=80',
        liked: true,
      },
    ],
  },
  {
    id: 'kpop-crl',
    title: 'kpop e os crl',
    subtitle: 'Playlist • Jão',
    author: 'Jão',
    coverUrl: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=600&q=80',
    coverSource: require('../../assets/images/kpop-cover.png'),
    isDownloaded: false,
    tracksCount: 10,
    tracks: [
      {
        id: 'kpop-1',
        title: 'Super Shy',
        artist: 'NewJeans',
        album: 'Get Up',
        duration: '2:34',
        durationSeconds: 154,
        coverUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&q=80',
        liked: true,
      },
      {
        id: 'kpop-2',
        title: 'Dynamite',
        artist: 'BTS',
        album: 'BE',
        duration: '3:19',
        durationSeconds: 199,
        coverUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80',
        liked: true,
      },
      {
        id: 'kpop-3',
        title: 'Pink Venom',
        artist: 'BLACKPINK',
        album: 'BORN PINK',
        duration: '3:06',
        durationSeconds: 186,
        coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&q=80',
        liked: true,
      },
      {
        id: 'kpop-4',
        title: 'ANTIFRAGILE',
        artist: 'LE SSERAFIM',
        album: 'ANTIFRAGILE',
        duration: '3:04',
        durationSeconds: 184,
        coverUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=600&q=80',
        liked: true,
      },
      {
        id: 'kpop-5',
        title: "God's Menu",
        artist: 'Stray Kids',
        album: 'GO生 (GO LIVE)',
        duration: '2:48',
        durationSeconds: 168,
        coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&q=80',
        liked: false,
      },
      {
        id: 'kpop-6',
        title: 'Ditto',
        artist: 'NewJeans',
        album: 'OMG',
        duration: '3:05',
        durationSeconds: 185,
        coverUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&q=80',
        liked: true,
      },
      {
        id: 'kpop-7',
        title: 'Hype Boy',
        artist: 'NewJeans',
        album: 'New Jeans',
        duration: '2:59',
        durationSeconds: 179,
        coverUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&q=80',
        liked: true,
      },
      {
        id: 'kpop-8',
        title: 'How You Like That',
        artist: 'BLACKPINK',
        album: 'THE ALBUM',
        duration: '3:01',
        durationSeconds: 181,
        coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&q=80',
        liked: true,
      },
      {
        id: 'kpop-9',
        title: 'Boy With Luv',
        artist: 'BTS, Halsey',
        album: 'Map of the Soul: Persona',
        duration: '3:49',
        durationSeconds: 229,
        coverUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&q=80',
        liked: false,
      },
      {
        id: 'kpop-10',
        title: 'FEARLESS',
        artist: 'LE SSERAFIM',
        album: 'FEARLESS',
        duration: '2:48',
        durationSeconds: 168,
        coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&q=80',
        liked: true,
      },
    ],
  },
];

// Categorias e Gêneros da Tela de Busca
export const SEARCH_CATEGORIES: Category[] = [
  { id: 'musica', title: 'Música', color: '#E8115B', imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=200&q=80' },
  { id: 'podcasts', title: 'Podcasts', color: '#148A08', imageUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=200&q=80' },
  { id: 'eventos', title: 'Eventos ao vivo', color: '#7358FF', imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=200&q=80' },
  { id: 'fitness', title: 'Fitness', color: '#503750', imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=200&q=80' },
  { id: 'brasil', title: 'Feito para você', color: '#1E3264', imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200&q=80' },
  { id: 'radar', title: 'Próximos lançamentos', color: '#006450', imageUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=200&q=80' },
  { id: 'rock', title: 'Rock', color: '#BC5900', imageUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=200&q=80' },
  { id: 'mpb', title: 'MPB', color: '#E91429', imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=200&q=80' },
];

export interface UserProfileData {
  name: string;
  plan: string;
  avatarUrl: string;
  avatarSource?: ImageSourcePropType;
}

// Usuário logado
export const USER_PROFILE: UserProfileData = {
  name: 'Jão',
  plan: 'Universitário',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80',
  avatarSource: require('../../assets/images/jao-profile.jpg'),
};

// Amigos e Atividades com Playlists Exclusivas e Diferenciadas
export const FRIENDS_ACTIVITY: FriendActivity[] = [
  {
    id: 'friend-1',
    name: 'Gabriela',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&q=80',
    currentTrack: 'sangrar',
    currentArtist: 'Arthur',
    lastActive: 'Ouvindo agora',
    playlists: [
      {
        id: 'gabi-indie-vibes',
        title: 'Indie & Sad Girl',
        subtitle: 'Playlist • Gabriela',
        author: 'Gabriela',
        coverUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&q=80',
        tracksCount: 6,
        tracks: [
          {
            id: 'gabi-1',
            title: 'sangrar',
            artist: 'Arthur',
            album: 'Coração Partido',
            duration: '3:15',
            durationSeconds: 195,
            coverUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80',
            liked: false,
          },
          {
            id: 'gabi-2',
            title: 'Cardigan',
            artist: 'Taylor Swift',
            album: 'folklore',
            duration: '3:59',
            durationSeconds: 239,
            coverUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400&q=80',
            liked: true,
          },
          {
            id: 'gabi-3',
            title: 'Video Games',
            artist: 'Lana Del Rey',
            album: 'Born to Die',
            duration: '4:42',
            durationSeconds: 282,
            coverUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
            liked: true,
          },
          {
            id: 'gabi-4',
            title: 'Motion Sickness',
            artist: 'Phoebe Bridgers',
            album: 'Stranger in the Alps',
            duration: '3:49',
            durationSeconds: 229,
            coverUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80',
            liked: true,
          },
          {
            id: 'gabi-5',
            title: 'Space Song',
            artist: 'Beach House',
            album: 'Depression Cherry',
            duration: '5:20',
            durationSeconds: 320,
            coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80',
            liked: false,
          },
          {
            id: 'gabi-6',
            title: 'The Night We Met',
            artist: 'Lord Huron',
            album: 'Strange Trails',
            duration: '3:28',
            durationSeconds: 208,
            coverUrl: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=400&q=80',
            liked: true,
          },
        ],
      },
      {
        id: 'gabi-pop-hits',
        title: 'Acoustic Sunday',
        subtitle: 'Playlist • Gabriela',
        author: 'Gabriela',
        coverUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=600&q=80',
        tracksCount: 6,
        tracks: [
          {
            id: 'gabi-acoustic-1',
            title: 'Banana Pancakes',
            artist: 'Jack Johnson',
            album: 'In Between Dreams',
            duration: '3:12',
            durationSeconds: 192,
            coverUrl: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400&q=80',
            liked: true,
          },
          {
            id: 'gabi-acoustic-2',
            title: 'Put Your Records On',
            artist: 'Corinne Bailey Rae',
            album: 'Corinne Bailey Rae',
            duration: '3:35',
            durationSeconds: 215,
            coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&q=80',
            liked: true,
          },
          {
            id: 'gabi-acoustic-3',
            title: 'Better Together',
            artist: 'Jack Johnson',
            album: 'In Between Dreams',
            duration: '3:27',
            durationSeconds: 207,
            coverUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80',
            liked: false,
          },
          {
            id: 'gabi-acoustic-4',
            title: 'Fast Car',
            artist: 'Tracy Chapman',
            album: 'Tracy Chapman',
            duration: '4:56',
            durationSeconds: 296,
            coverUrl: 'https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=400&q=80',
            liked: true,
          },
          {
            id: 'gabi-acoustic-5',
            title: 'Sunday Morning',
            artist: 'Maroon 5',
            album: 'Songs About Jane',
            duration: '4:02',
            durationSeconds: 242,
            coverUrl: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=400&q=80',
            liked: true,
          },
          {
            id: 'gabi-acoustic-6',
            title: 'Here Comes The Sun',
            artist: 'The Beatles',
            album: 'Abbey Road',
            duration: '3:05',
            durationSeconds: 185,
            coverUrl: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=400&q=80',
            liked: true,
          },
        ],
      },
    ],
  },
  {
    id: 'friend-2',
    name: 'Márcio Garrido',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
    avatarSource: require('../../assets/images/marcio-garrido.png'),
    currentTrack: 'Back in Black',
    currentArtist: 'AC/DC',
    lastActive: 'Ouvindo no talo',
    playlists: [
      {
        id: 'garrido-hard-rock',
        title: 'Hard Rock Classics',
        subtitle: 'Playlist • Márcio Garrido',
        author: 'Márcio Garrido',
        coverUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=600&q=80',
        tracksCount: 6,
        tracks: [
          {
            id: 'rock-1',
            title: 'Back in Black',
            artist: 'AC/DC',
            album: 'Back in Black',
            duration: '4:15',
            durationSeconds: 255,
            coverUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=400&q=80',
            liked: true,
          },
          {
            id: 'rock-2',
            title: 'Highway to Hell',
            artist: 'AC/DC',
            album: 'Highway to Hell',
            duration: '3:28',
            durationSeconds: 208,
            coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&q=80',
            liked: true,
          },
          {
            id: 'rock-3',
            title: 'Thunderstruck',
            artist: 'AC/DC',
            album: 'The Razors Edge',
            duration: '4:52',
            durationSeconds: 292,
            coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&q=80',
            liked: true,
          },
          {
            id: 'rock-4',
            title: "Sweet Child O' Mine",
            artist: "Guns N' Roses",
            album: 'Appetite for Destruction',
            duration: '5:56',
            durationSeconds: 356,
            coverUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400&q=80',
            liked: true,
          },
          {
            id: 'rock-5',
            title: 'Smoke on the Water',
            artist: 'Deep Purple',
            album: 'Machine Head',
            duration: '5:40',
            durationSeconds: 340,
            coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&q=80',
            liked: true,
          },
          {
            id: 'rock-6',
            title: 'You Shook Me All Night Long',
            artist: 'AC/DC',
            album: 'Back in Black',
            duration: '3:30',
            durationSeconds: 210,
            coverUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=400&q=80',
            liked: true,
          },
        ],
      },
      {
        id: 'garrido-metal-workout',
        title: 'Heavy Metal & Code',
        subtitle: 'Playlist • Márcio Garrido',
        author: 'Márcio Garrido',
        coverUrl: 'https://images.unsplash.com/photo-1464375117522-1311d6a5b81f?w=600&q=80',
        tracksCount: 6,
        tracks: [
          {
            id: 'metal-1',
            title: 'Master of Puppets',
            artist: 'Metallica',
            album: 'Master of Puppets',
            duration: '8:35',
            durationSeconds: 515,
            coverUrl: 'https://images.unsplash.com/photo-1464375117522-1311d6a5b81f?w=400&q=80',
            liked: true,
          },
          {
            id: 'metal-2',
            title: 'The Trooper',
            artist: 'Iron Maiden',
            album: 'Piece of Mind',
            duration: '4:11',
            durationSeconds: 251,
            coverUrl: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=400&q=80',
            liked: true,
          },
          {
            id: 'metal-3',
            title: 'Paranoid',
            artist: 'Black Sabbath',
            album: 'Paranoid',
            duration: '2:49',
            durationSeconds: 169,
            coverUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&q=80',
            liked: true,
          },
          {
            id: 'metal-4',
            title: 'Fear of the Dark',
            artist: 'Iron Maiden',
            album: 'Fear of the Dark',
            duration: '7:18',
            durationSeconds: 438,
            coverUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&q=80',
            liked: true,
          },
          {
            id: 'metal-5',
            title: 'Symphony of Destruction',
            artist: 'Megadeth',
            album: 'Countdown to Extinction',
            duration: '4:02',
            durationSeconds: 242,
            coverUrl: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=400&q=80',
            liked: false,
          },
          {
            id: 'metal-6',
            title: 'Enter Sandman',
            artist: 'Metallica',
            album: 'Metallica',
            duration: '5:31',
            durationSeconds: 331,
            coverUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400&q=80',
            liked: true,
          },
        ],
      },
    ],
  },
  {
    id: 'friend-3',
    name: 'Camila',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80',
    currentTrack: 'SaWaDiKa',
    currentArtist: 'Fic',
    lastActive: 'Há 1h',
    playlists: [
      {
        id: 'camila-lofi-beats',
        title: 'Lo-Fi Study Beats',
        subtitle: 'Playlist • Camila',
        author: 'Camila',
        coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80',
        tracksCount: 6,
        tracks: [
          {
            id: 'camila-1',
            title: 'SaWaDiKa',
            artist: 'Fic',
            album: 'Oriental Moods',
            duration: '2:40',
            durationSeconds: 160,
            coverUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&q=80',
            liked: false,
          },
          {
            id: 'camila-2',
            title: 'Coffee in Rain',
            artist: 'Chilled Cow',
            album: 'Lofi Sessions',
            duration: '2:12',
            durationSeconds: 132,
            coverUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=400&q=80',
            liked: true,
          },
          {
            id: 'camila-3',
            title: 'Controlla',
            artist: 'Idealism',
            album: 'Hiraeth',
            duration: '2:25',
            durationSeconds: 145,
            coverUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&q=80',
            liked: true,
          },
          {
            id: 'camila-4',
            title: 'Again',
            artist: 'Wun Two',
            album: 'Rio',
            duration: '1:58',
            durationSeconds: 118,
            coverUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&q=80',
            liked: false,
          },
          {
            id: 'camila-5',
            title: 'Affection',
            artist: 'Jinsang',
            album: 'Life',
            duration: '2:45',
            durationSeconds: 165,
            coverUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80',
            liked: true,
          },
          {
            id: 'camila-6',
            title: 'feelings',
            artist: 'potsu',
            album: 'late night sessions',
            duration: '2:06',
            durationSeconds: 126,
            coverUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=400&q=80',
            liked: true,
          },
        ],
      },
      {
        id: 'camila-jazz-focus',
        title: 'Jazz para focar',
        subtitle: 'Playlist • Camila',
        author: 'Camila',
        coverUrl: 'https://images.unsplash.com/photo-1525994886773-080587e161c2?w=600&q=80',
        tracksCount: 6,
        tracks: [
          {
            id: 'camila-jazz-1',
            title: 'Blue in Green',
            artist: 'Miles Davis',
            album: 'Kind of Blue',
            duration: '5:37',
            durationSeconds: 337,
            coverUrl: 'https://images.unsplash.com/photo-1525994886773-080587e161c2?w=400&q=80',
            liked: true,
          },
          {
            id: 'camila-jazz-2',
            title: 'Autumn Leaves',
            artist: 'Bill Evans Trio',
            album: 'Portrait in Jazz',
            duration: '6:02',
            durationSeconds: 362,
            coverUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=400&q=80',
            liked: false,
          },
          {
            id: 'camila-jazz-3',
            title: 'Take Five',
            artist: 'The Dave Brubeck Quartet',
            album: 'Time Out',
            duration: '5:24',
            durationSeconds: 324,
            coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&q=80',
            liked: true,
          },
          {
            id: 'camila-jazz-4',
            title: 'My Favorite Things',
            artist: 'John Coltrane',
            album: 'My Favorite Things',
            duration: '13:41',
            durationSeconds: 821,
            coverUrl: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=400&q=80',
            liked: true,
          },
          {
            id: 'camila-jazz-5',
            title: "Round Midnight",
            artist: 'Thelonious Monk',
            album: 'Round Midnight',
            duration: '3:11',
            durationSeconds: 191,
            coverUrl: 'https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=400&q=80',
            liked: false,
          },
          {
            id: 'camila-jazz-6',
            title: 'So What',
            artist: 'Miles Davis',
            album: 'Kind of Blue',
            duration: '9:22',
            durationSeconds: 562,
            coverUrl: 'https://images.unsplash.com/photo-1445985543470-41f30c08f107?w=400&q=80',
            liked: true,
          },
        ],
      },
    ],
  },
  {
    id: 'friend-4',
    name: 'Lucas Ferreira',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80',
    currentTrack: 'Evidências',
    currentArtist: 'Chitãozinho & Xororó',
    lastActive: 'Ativado',
    playlists: [
      {
        id: 'lucas-sertanejo',
        title: 'Sertanejo Raiz',
        subtitle: 'Playlist • Lucas Ferreira',
        author: 'Lucas Ferreira',
        coverUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&q=80',
        tracksCount: 6,
        tracks: [
          {
            id: 'lucas-1',
            title: 'Evidências',
            artist: 'Chitãozinho & Xororó',
            album: 'Cowboy do Asfalto',
            duration: '4:39',
            durationSeconds: 279,
            coverUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=400&q=80',
            liked: true,
          },
          {
            id: 'lucas-2',
            title: 'Fio de Cabelo',
            artist: 'Chitãozinho & Xororó',
            album: 'Somos Assim',
            duration: '2:48',
            durationSeconds: 168,
            coverUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=400&q=80',
            liked: true,
          },
          {
            id: 'lucas-3',
            title: 'Pense em Mim',
            artist: 'Leandro & Leonardo',
            album: 'Volume 4',
            duration: '3:18',
            durationSeconds: 198,
            coverUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=400&q=80',
            liked: false,
          },
          {
            id: 'lucas-4',
            title: 'O Menino da Porteira',
            artist: 'Sérgio Reis',
            album: 'O Menino da Porteira',
            duration: '3:35',
            durationSeconds: 215,
            coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&q=80',
            liked: true,
          },
          {
            id: 'lucas-5',
            title: 'Nuvem de Lágrimas',
            artist: 'Chitãozinho & Xororó',
            album: 'Nuvem de Lágrimas',
            duration: '4:10',
            durationSeconds: 250,
            coverUrl: 'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=400&q=80',
            liked: true,
          },
          {
            id: 'lucas-6',
            title: 'Boate Azul',
            artist: 'Joaquim & Manuel',
            album: 'Boate Azul',
            duration: '3:12',
            durationSeconds: 192,
            coverUrl: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=400&q=80',
            liked: false,
          },
        ],
      },
      {
        id: 'lucas-modao',
        title: 'Modao de Estrada',
        subtitle: 'Playlist • Lucas Ferreira',
        author: 'Lucas Ferreira',
        coverUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=600&q=80',
        tracksCount: 6,
        tracks: [
          {
            id: 'lucas-modao-1',
            title: 'Romaria',
            artist: 'Renato Teixeira',
            album: 'Romaria',
            duration: '3:57',
            durationSeconds: 237,
            coverUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=400&q=80',
            liked: true,
          },
          {
            id: 'lucas-modao-2',
            title: 'Tocando em Frente',
            artist: 'Almir Sater',
            album: 'Tocando em Frente',
            duration: '3:31',
            durationSeconds: 211,
            coverUrl: 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=400&q=80',
            liked: true,
          },
          {
            id: 'lucas-modao-3',
            title: 'Telefone Mudo',
            artist: 'Trio Parada Dura',
            album: 'As Romanticas',
            duration: '3:19',
            durationSeconds: 199,
            coverUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=400&q=80',
            liked: false,
          },
          {
            id: 'lucas-modao-4',
            title: 'Chalana',
            artist: 'Almir Sater',
            album: 'Cria',
            duration: '3:24',
            durationSeconds: 204,
            coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80',
            liked: true,
          },
          {
            id: 'lucas-modao-5',
            title: 'Um Violeiro Toca',
            artist: 'Almir Sater',
            album: 'Terra dos Sonhos',
            duration: '3:45',
            durationSeconds: 225,
            coverUrl: 'https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=400&q=80',
            liked: true,
          },
          {
            id: 'lucas-modao-6',
            title: 'As Andorinhas',
            artist: 'Trio Parada Dura',
            album: 'Alto Astral',
            duration: '3:08',
            durationSeconds: 188,
            coverUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=400&q=80',
            liked: false,
          },
        ],
      },
    ],
  },
];

// Mensagens diretas com histórico de conversa completo
export const DIRECT_MESSAGES: DirectMessage[] = [
  {
    id: 'dm-1',
    senderName: 'Mariana Costa',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&q=80',
    previewText: 'compartilhou 1 música',
    date: '8 de abr.',
    messages: [
      {
        id: 'msg-1',
        sender: 'them',
        text: 'E aí Jão! Já ouviu esse som novo?',
        time: '14:20',
      },
      {
        id: 'msg-2',
        sender: 'them',
        text: 'Dá uma olhada, achei muito a sua cara:',
        time: '14:21',
        sharedTrack: CURRENT_TRACK,
      },
      {
        id: 'msg-3',
        sender: 'me',
        text: 'Nossa, bom demais! Já adicionei na minha playlist.',
        time: '14:25',
      },
    ],
  },
  {
    id: 'dm-2',
    senderName: 'Felipe Santos',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&q=80',
    previewText: 'Enviou uma recomendação',
    date: '7 de mar.',
    messages: [
      {
        id: 'msg-201',
        sender: 'them',
        text: 'Mano, aquele álbum do Cazuza que você tava ouvindo é sensacional',
        time: '18:05',
      },
      {
        id: 'msg-202',
        sender: 'me',
        text: 'Exagerado né? Um clássico atemporal!',
        time: '18:10',
      },
    ],
  },
];
